# -*- coding: utf-8 -*-
"""Feature scaling Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKLfCuyH66zAriqFMPRqihhlEiXMcnOP

Importing necessary libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Load the Datasets"""

train_path = "/content/processed_Train_data.csv"
train_df = pd.read_csv(train_path)

print("Train Dataset")
display(train_df.head())

"""Visualize Data Before Log Transformation"""

# Select numerical columns
num_cols = ["luxury_sales", "fresh_sales", "dry_sales"]

# Create subplots for visualization
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for i, col in enumerate(num_cols):
    sns.histplot(train_df[col], bins=30, kde=True, ax=axes[i])
    axes[i].set_title(f"Before Log Transformation: {col}")

plt.tight_layout()
plt.show()

"""Apply Log Transformation"""

train_df[num_cols] = train_df[num_cols].apply(lambda x: np.log1p(x))

"""Visualize Data After Log Transformation"""

# Create subplots for visualization after log transform
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for i, col in enumerate(num_cols):
    sns.histplot(train_df[col], bins=30, kde=True, ax=axes[i])
    axes[i].set_title(f"After Log Transformation: {col}")

plt.tight_layout()
plt.show()

"""Feature scaling"""

from sklearn.preprocessing import MinMaxScaler

# Select numerical columns to scale
features_to_scale = ['luxury_sales', 'fresh_sales', 'dry_sales']

# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Fit on training data and transform both train & test sets
train_df[features_to_scale] = scaler.fit_transform(train_df[features_to_scale])

print("Feature Scaling Completed!")

# Preview first few rows of the scaled train dataset
print("\nPreview of Scaled Train Data:")
print(train_df.head())

"""Prepare Data for Model Training"""

train_df.drop(columns=['Customer_ID', 'outlet_city'], inplace=True)

# Save the scaled dataset
output_path = "/content/Scaled_Train_data.csv"
train_df.to_csv(output_path, index=False)